#!/bin/bash

VIDEO_URL="https://drive.google.com/uc?export=download&id=1Wj6CPrKOmmsc__AVVM0nGNrXpyazBwdP"
AUDIO_URL="https://drive.google.com/uc?export=download&id=15-YDwagtDAf9dWLzgeQCEfbHobovKOBA"

VIDEO_INPUT="input_video.mp4"
AUDIO_INPUT="input_audio.mp3"
MONETIZED_OUTPUT="LofiMellowHQ_Final.mp4"

echo "Downloading..."
wget -O "$VIDEO_INPUT" "$VIDEO_URL"
wget -O "$AUDIO_INPUT" "$AUDIO_URL"

echo "Rendering..."

ffmpeg -y \
  -stream_loop -1 -i "$VIDEO_INPUT" \
  -i "$AUDIO_INPUT" \
  -filter_complex "[0:v]scale=1920:1080,setpts=PTS-STARTPTS[v]" \
  -map "[v]" \
  -map 1:a \
  -c:v libx264 \
  -preset slow \
  -crf 16 \
  -r 30 \
  -pix_fmt yuv420p \
  -c:a aac -b:a 320k \
  -ar 48000 \
  -shortest \
  -metadata title="Cozy Thunderstorm Cabin Lofi" \
  -metadata artist="LofiMellow HQ" \
  -metadata album="Rain and Thunder" \
  -metadata genre="Lo-fi" \
  -metadata copyright="2026 LofiMellow HQ" \
  -metadata comment="LofiMellow HQ - Original Content" \
  -movflags +faststart \
  "$MONETIZED_OUTPUT"

echo "Done!"
